name: librecad
version: '0.0.9'
grade: stable
base: core18
confinement: devmode
summary: "librecad: is a cad"
description: |
        it really is.
environment:
        LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/:$SNAP/usr/lib64:$LD_LIBRARY_PATH

apps:
        librecad:
                command: usr/bin/librecad 
                extensions:
                        - kde-neon
parts:
        librecad:
                plugin: cmake
                build-snaps:
                        - kde-frameworks-5-core18-sdk
                        - kde-frameworks-5-core18
                          #I don't know if i need more packages
                source: .
                build-packages:
                        - qttools5-dev 
                        - qttools5-dev-tools 
                        - libqt5opengl5-dev
                        - liblua5.2-dev
                        - git
                        - g++
                        - libcairo2-dev
                        - libpango-1.0-0
                        - libpango1.0-dev
                        - libboost-dev
                        - libboost-log-dev
                        - libboost-program-options-dev
                        - libqt5svg5-dev
                        - libgtest-dev
                        - libeigen3-dev
                        - libcurl4-gnutls-dev
                        - libgtk-3-dev
                        - libglew-dev
                        - rapidjson-dev
                        - libbz2-dev
                        - libglfw3-dev
                        - libglm-dev
                        - cmake
                stage-packages:
                        - libboost-dev
                        - libboost-log-dev
                        - libboost-program-options-dev
                        - libglew2.0
                configflags:
                        - "-DCMAKE_INSTALL_PREFIX=/usr"
                        - "-DBUILD_SHARED_LIBS=On"
        libdxfrw:
                plugin: cmake
                source: ~/libdxfrw
                configflags:
                        - "-DBUILD_SHARED_LIBS=On"

