#pragma once

#include <cad/interface/metatype.h>
#include <vector>
#include <cad/geometry/geocoordinate.h>
#include "metacolor.h"
#include "dxflinepattern.h"
#include "metalinewidth.h"

#define BLOCK_ID_PREFIX "_BLOCK"

namespace lc {
namespace meta {
class Block : public DocumentMetaType {
public:
    /// @param anonymous  the source marked this block as generated by the
    ///                    application rather than by a user -- DXF's BLOCK
    ///                    code 70, bit 1. A writer that regenerates such a
    ///                    block needs to tell it apart from user content that
    ///                    happens to share the naming convention.
    Block(std::string name, geo::Coordinate base=geo::Coordinate(0,0),
          bool anonymous=false);

    const std::string id() const override;

    const std::string name() const override;

    const geo::Coordinate& base() const;

    /// Whether the source marked this block application-generated.
    bool anonymous() const;

    virtual const std::string metaTypeID() const {
        return Block::LCMETANAME();
    }

    static const std::string LCMETANAME() {
        return BLOCK_ID_PREFIX;
    }

private:
    std::string _name;
    geo::Coordinate _base;
    bool _anonymous;
};

DECLARE_SHORT_SHARED_PTR(Block)
}
}