require 'actions.operations'

require 'actions.moveoperation'
require 'actions.rotateoperation'
require 'actions.copyoperation'
require 'actions.scaleoperation'
require 'actions.removeoperation'
require 'actions.trimoperation'

require 'createActions.createOperations'
require 'createActions.ellipseoperations'
require 'createActions.lineoperations'
require 'createActions.splineoperations'
require 'createActions.circleoperations'
require 'createActions.arcoperations'
require 'createActions.lwpolylineoperations'
require 'createActions.dimalignedoperations'
require 'createActions.dimangularoperations'
require 'createActions.dimdiametricoperations'
require 'createActions.dimlinearoperations'
require 'createActions.dimradialoperations'

require 'optionActions.gridSnappable'