require 'actions.operations'
require 'createActions.createOperations'

require 'actions.lineoperations'
require 'actions.circleoperations'
require 'actions.arcoperations'
require 'actions.ellipseoperations'
require 'actions.dimalignedoperations'
require 'actions.dimangularoperations'
require 'actions.dimdiametricoperations'
require 'actions.dimlinearoperations'
require 'actions.dimradialoperations'
require 'actions.splineoperations'
require 'actions.lwpolylineoperations'

require 'actions.moveoperation'
require 'actions.rotateoperation'
require 'actions.copyoperation'
require 'actions.scaleoperation'
require 'actions.removeoperation'
require 'actions.trimoperation'