#ifndef LCADLUASCRIPT_GLOBAL_H
#define LCADLUASCRIPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LCADLUASCRIPT_LIBRARY)
#  define LCADLUASCRIPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LCADLUASCRIPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LCADLUASCRIPT_GLOBAL_H
